/**
 * Cowork Marketplace Seed Catalog
 *
 * Pre-built cowork items derived from the installed plugin ecosystem.
 * Each item maps to real plugin agents, skills, and commands so that
 * launching a cowork session actually invokes the underlying capabilities.
 *
 * This catalog covers all 15 installed plugins and their 129+ agents,
 * 53+ skills, and 142+ commands across engineering, DevOps, design,
 * finance, operations, home automation, and enterprise domains.
 */

import type { CoworkItem } from '@/types/cowork';

// ---------------------------------------------------------------------------
// Helper: create consistent IDs and timestamps
// ---------------------------------------------------------------------------

let _seq = 0;
const id = () => `cowork-${String(++_seq).padStart(3, '0')}`;
const now = '2026-02-28T00:00:00Z';

const author = {
  id: 'markus-ahling',
  name: 'Markus Ahling',
  avatarUrl: undefined,
  organization: 'Lobbi',
  isVerified: true,
  itemCount: 0, // patched below
};

const trust = (overall: number) => ({
  overall,
  grade: (overall >= 90 ? 'A' : overall >= 80 ? 'B' : overall >= 60 ? 'C' : overall >= 40 ? 'D' : 'F') as 'A' | 'B' | 'C' | 'D' | 'F',
  signed: Math.min(100, overall + 5),
  reputation: overall,
  codeAnalysis: Math.min(100, overall + 2),
  community: Math.max(0, overall - 5),
  freshness: Math.min(100, overall + 3),
});

// ---------------------------------------------------------------------------
// TEMPLATES  (quick-start session templates)
// ---------------------------------------------------------------------------

const templates: CoworkItem[] = [
  {
    id: id(),
    name: 'fastapi-scaffold',
    displayName: 'FastAPI Project Scaffold',
    version: '1.0.0',
    description: 'Scaffold a production-ready FastAPI backend with MongoDB/Beanie ODM, Keycloak auth, Docker, and Kubernetes manifests in one session.',
    type: 'template',
    category: 'engineering',
    difficulty: 'intermediate',
    status: 'featured',
    author,
    tags: ['python', 'fastapi', 'mongodb', 'keycloak', 'docker', 'kubernetes'],
    capabilities: [
      { name: 'API Scaffolding', description: 'Generate endpoint stubs, models, and schemas', tools: ['Write', 'Bash'] },
      { name: 'Auth Integration', description: 'Wire Keycloak OIDC with JWT middleware', tools: ['Read', 'Write'] },
      { name: 'Container Setup', description: 'Dockerfile, docker-compose, and K8s manifests', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'fastapi-backend', version: '>=0.1.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'fastapi-backend',
      pluginVersion: '0.1.0',
      agents: ['api-architect', 'test-generator', 'security-reviewer'],
      skills: ['fastapi-patterns', 'beanie-odm', 'keycloak-fastapi', 'fastapi-k8s'],
      commands: ['scaffold', 'model', 'endpoint', 'deploy', 'docker'],
    }],
    estimatedDuration: '15 min',
    maxParallelAgents: 3,
    installCount: 342,
    activeUsers: 89,
    averageRating: 4.7,
    ratingCount: 56,
    completionRate: 0.94,
    avgSessionMinutes: 12,
    trustScore: trust(92),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    repositoryUrl: 'https://github.com/Lobbi-Docs/claude',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'fullstack-react-fastapi',
    displayName: 'Full-Stack React + FastAPI',
    version: '1.0.0',
    description: 'Generate a complete full-stack application with React/Vite frontend, FastAPI backend, Ansible provisioning, Terraform IaC, and Docker orchestration.',
    type: 'template',
    category: 'engineering',
    difficulty: 'advanced',
    status: 'published',
    author,
    tags: ['react', 'fastapi', 'terraform', 'ansible', 'full-stack'],
    capabilities: [
      { name: 'Frontend Generation', description: 'React + Vite + Tailwind setup with routing', tools: ['Write', 'Bash'] },
      { name: 'Backend Generation', description: 'FastAPI with database models and auth', tools: ['Write', 'Bash'] },
      { name: 'Infrastructure as Code', description: 'Terraform modules + Ansible playbooks', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'fullstack-iac', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'fastapi-backend', version: '>=0.1.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [
      {
        pluginName: 'fullstack-iac',
        pluginVersion: '1.0.0',
        agents: ['api-architect', 'frontend-builder'],
        skills: ['fastapi-patterns', 'react-vite'],
        commands: ['new', 'frontend', 'api', 'infra', 'docker', 'k8s', 'ansible', 'monorepo'],
      },
      {
        pluginName: 'fastapi-backend',
        pluginVersion: '0.1.0',
        agents: ['api-architect', 'performance-optimizer'],
        skills: ['fastapi-patterns', 'fastapi-realtime'],
        commands: ['scaffold', 'endpoint', 'model'],
      },
    ],
    estimatedDuration: '25 min',
    maxParallelAgents: 4,
    installCount: 198,
    activeUsers: 45,
    averageRating: 4.5,
    ratingCount: 34,
    completionRate: 0.88,
    avgSessionMinutes: 22,
    trustScore: trust(90),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'home-assistant-setup',
    displayName: 'Smart Home Assistant Setup',
    version: '2.0.0',
    description: 'Configure a complete Home Assistant deployment with energy management, camera NVR, automations, sensors, voice assistant, and local LLM via Ollama on Ubuntu.',
    type: 'template',
    category: 'engineering',
    difficulty: 'intermediate',
    status: 'featured',
    author,
    tags: ['home-assistant', 'smart-home', 'iot', 'ollama', 'automation', 'ubuntu'],
    capabilities: [
      { name: 'HA Deployment', description: 'Install and configure Home Assistant on Ubuntu', tools: ['Bash', 'Write'] },
      { name: 'Automation Design', description: 'Create YAML automations for lights, climate, security', tools: ['Write'] },
      { name: 'Energy Optimization', description: 'Solar tracking, battery management, cost optimization', tools: ['Read', 'Write'] },
      { name: 'Local LLM', description: 'Deploy Ollama for on-device AI processing', tools: ['Bash'] },
    ],
    dependencies: [
      { name: 'home-assistant-architect', version: '>=2.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'home-assistant-architect',
      pluginVersion: '2.0.0',
      agents: ['ha-automation-architect', 'ha-energy-optimizer', 'ha-dashboard-designer', 'ha-camera-nvr', 'ha-sensor-manager', 'ha-voice-assistant', 'local-llm-manager', 'ubuntu-ha-deployer'],
      skills: ['ha-core', 'ha-automation', 'energy-management', 'camera-nvr', 'local-llm', 'lovelace-design', 'sensor-management', 'ubuntu-deployment'],
      commands: ['ha-deploy', 'ha-automation', 'ha-energy', 'ha-camera', 'ha-sensor', 'ha-dashboard', 'ha-control', 'ollama-setup'],
    }],
    estimatedDuration: '30 min',
    maxParallelAgents: 5,
    installCount: 276,
    activeUsers: 112,
    averageRating: 4.8,
    ratingCount: 78,
    completionRate: 0.91,
    avgSessionMinutes: 28,
    trustScore: trust(95),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// WORKFLOWS  (multi-step automated workflows)
// ---------------------------------------------------------------------------

const workflows: CoworkItem[] = [
  {
    id: id(),
    name: 'jira-to-pr',
    displayName: 'Jira Issue to Pull Request',
    version: '7.5.0',
    description: 'Complete end-to-end workflow: analyze Jira issue, create branch, implement code changes with TDD, run quality gates, create PR with smart commit linking, and update Jira status.',
    type: 'workflow',
    category: 'engineering',
    difficulty: 'intermediate',
    status: 'featured',
    author,
    tags: ['jira', 'git', 'tdd', 'code-review', 'ci-cd', 'harness'],
    capabilities: [
      { name: 'Issue Analysis', description: 'Parse Jira issue, decompose into subtasks', tools: ['Read', 'Bash'] },
      { name: 'Branch & Code', description: 'Create branch, implement with TDD, lint, test', tools: ['Write', 'Edit', 'Bash'] },
      { name: 'Quality Gates', description: 'Type check, lint, security scan, test coverage', tools: ['Bash'] },
      { name: 'PR Creation', description: 'Smart commit messages, PR with linked Jira issue', tools: ['Bash'] },
    ],
    dependencies: [
      { name: 'jira-orchestrator', version: '>=7.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'jira-orchestrator',
      pluginVersion: '7.5.0',
      agents: ['commit-orchestrator', 'code-reviewer', 'code-quality-enforcer', 'commit-message-generator', 'checkpoint-pr-manager'],
      skills: ['jira-orchestration', 'pr-workflow', 'code-review', 'clean-architecture'],
      commands: ['work', 'branch', 'commit', 'pr', 'review', 'status', 'sync'],
    }],
    estimatedDuration: '20 min',
    maxParallelAgents: 4,
    installCount: 567,
    activeUsers: 203,
    averageRating: 4.9,
    ratingCount: 142,
    completionRate: 0.96,
    avgSessionMinutes: 18,
    trustScore: trust(97),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'eks-deploy-pipeline',
    displayName: 'AWS EKS Deployment Pipeline',
    version: '1.0.0',
    description: 'Automated deployment pipeline: build Docker images, push to ECR, deploy Helm charts to EKS with Keycloak OIDC, configure Harness CD pipelines, run smoke tests.',
    type: 'workflow',
    category: 'devops',
    difficulty: 'advanced',
    status: 'published',
    author,
    tags: ['aws', 'eks', 'kubernetes', 'helm', 'keycloak', 'harness', 'ci-cd'],
    capabilities: [
      { name: 'Docker Build', description: 'Multi-stage builds, ECR push, image scanning', tools: ['Bash'] },
      { name: 'Helm Deploy', description: 'Chart packaging, values templating, atomic rollout', tools: ['Bash', 'Write'] },
      { name: 'OIDC Auth', description: 'Keycloak integration with EKS service accounts', tools: ['Bash', 'Write'] },
      { name: 'Harness Pipeline', description: 'Generate Harness CD pipeline configuration', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'aws-eks-helm-keycloak', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'deployment-pipeline', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [
      {
        pluginName: 'aws-eks-helm-keycloak',
        pluginVersion: '1.0.0',
        agents: ['deployment-strategist', 'pipeline-architect', 'setup-orchestrator'],
        skills: ['harness-eks-deployments', 'harness-keycloak-auth', 'helm-development', 'local-eks-development'],
        commands: ['setup', 'ship', 'dev-up', 'preview', 'pipeline-scaffold', 'service-onboard'],
      },
      {
        pluginName: 'deployment-pipeline',
        pluginVersion: '1.0.0',
        agents: ['orchestrator', 'validator', 'rollback'],
        skills: [],
        commands: ['start', 'status', 'approve', 'rollback', 'history'],
      },
    ],
    estimatedDuration: '35 min',
    maxParallelAgents: 3,
    installCount: 156,
    activeUsers: 43,
    averageRating: 4.6,
    ratingCount: 28,
    completionRate: 0.85,
    avgSessionMinutes: 32,
    trustScore: trust(91),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'microsoft-platform-deploy',
    displayName: 'Microsoft Platform Deployment',
    version: '1.1.0',
    description: 'Deploy the full Microsoft ecosystem: Dataverse environments, Fabric workspaces, Power Platform solutions, Entra identity, Teams integrations, and Azure resources with cost tracking.',
    type: 'workflow',
    category: 'devops',
    difficulty: 'expert',
    status: 'published',
    author,
    tags: ['microsoft', 'azure', 'dataverse', 'fabric', 'power-platform', 'entra', 'teams'],
    capabilities: [
      { name: 'Dataverse Setup', description: 'Environment provisioning, entity configuration, ALM', tools: ['Bash', 'Write'] },
      { name: 'Fabric Workspace', description: 'Lakehouse, notebooks, pipeline authoring', tools: ['Bash', 'Write'] },
      { name: 'Identity Management', description: 'Entra app registrations, RBAC, conditional access', tools: ['Bash'] },
      { name: 'Teams Integration', description: 'App deployment, tabs, bots, channel configuration', tools: ['Bash', 'Write'] },
    ],
    dependencies: [
      { name: 'tvs-microsoft-deploy', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'tvs-microsoft-deploy',
      pluginVersion: '1.1.0',
      agents: ['platform-agent', 'azure-agent', 'data-agent', 'identity-agent', 'fabric-pipeline-agent', 'comms-agent', 'analytics-agent'],
      skills: ['az-cli', 'pac-cli', 'fabric-rest', 'graph-api', 'power-automate-rest', 'stripe-integration', 'dataverse-architecture', 'fabric-engineering'],
      commands: ['deploy-all', 'deploy-azure', 'deploy-dataverse', 'deploy-fabric', 'deploy-identity', 'deploy-portal', 'deploy-teams', 'status-check', 'cost-report'],
    }],
    estimatedDuration: '45 min',
    maxParallelAgents: 7,
    installCount: 89,
    activeUsers: 22,
    averageRating: 4.4,
    ratingCount: 15,
    completionRate: 0.82,
    avgSessionMinutes: 40,
    trustScore: trust(88),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'sprint-planning-automation',
    displayName: 'Sprint Planning Automation',
    version: '7.5.0',
    description: 'Automated sprint planning: capacity calculation, backlog prioritization, story point estimation, dependency mapping, risk assessment, and sprint board setup with Jira sync.',
    type: 'workflow',
    category: 'operations',
    difficulty: 'intermediate',
    status: 'published',
    author,
    tags: ['jira', 'scrum', 'sprint', 'planning', 'agile', 'estimation'],
    capabilities: [
      { name: 'Capacity Planning', description: 'Team velocity, availability, capacity calculation', tools: ['Read', 'Bash'] },
      { name: 'Backlog Grooming', description: 'Priority scoring, dependency analysis, risk assessment', tools: ['Read', 'Write'] },
      { name: 'Sprint Setup', description: 'Create sprint, assign issues, set goals', tools: ['Bash'] },
    ],
    dependencies: [
      { name: 'jira-orchestrator', version: '>=7.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'jira-orchestrator',
      pluginVersion: '7.5.0',
      agents: ['dependency-mapper', 'sprint-planner'],
      skills: ['jira-orchestration', 'task-details', 'triage'],
      commands: ['sprint-plan', 'sprint', 'triage', 'prepare', 'metrics', 'team'],
    }],
    estimatedDuration: '15 min',
    maxParallelAgents: 2,
    installCount: 234,
    activeUsers: 87,
    averageRating: 4.6,
    ratingCount: 52,
    completionRate: 0.93,
    avgSessionMinutes: 12,
    trustScore: trust(94),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// AGENT CONFIGS  (specialized agent configurations)
// ---------------------------------------------------------------------------

const agentConfigs: CoworkItem[] = [
  {
    id: id(),
    name: 'enterprise-code-reviewer',
    displayName: 'Enterprise Code Reviewer',
    version: '1.0.0',
    description: 'Multi-agent code review with security scanning, performance analysis, clean architecture enforcement, accessibility audit, and Harness PR integration.',
    type: 'agent_config',
    category: 'engineering',
    difficulty: 'intermediate',
    status: 'featured',
    author,
    tags: ['code-review', 'security', 'performance', 'clean-architecture', 'harness'],
    capabilities: [
      { name: 'Security Scan', description: 'OWASP top 10, credential exposure, injection detection', tools: ['Bash', 'Grep'] },
      { name: 'Performance Analysis', description: 'Bundle size, render performance, query optimization', tools: ['Bash', 'Read'] },
      { name: 'Architecture Review', description: 'SOLID principles, dependency direction, layer violations', tools: ['Read', 'Grep'] },
    ],
    dependencies: [
      { name: 'jira-orchestrator', version: '>=7.0.0', type: 'plugin', optional: false },
      { name: 'team-accelerator', version: '>=1.0.0', type: 'plugin', optional: true },
    ],
    pluginBindings: [
      {
        pluginName: 'jira-orchestrator',
        pluginVersion: '7.5.0',
        agents: ['code-reviewer', 'code-quality-enforcer', 'council-coordinator'],
        skills: ['code-review', 'clean-architecture'],
        commands: ['review', 'council', 'quality', 'harness-review'],
      },
      {
        pluginName: 'team-accelerator',
        pluginVersion: '1.0.0',
        agents: ['code-reviewer', 'performance-engineer'],
        skills: ['code-quality'],
        commands: ['quality', 'perf'],
      },
    ],
    estimatedDuration: '10 min',
    maxParallelAgents: 5,
    installCount: 423,
    activeUsers: 156,
    averageRating: 4.8,
    ratingCount: 98,
    completionRate: 0.97,
    avgSessionMinutes: 8,
    trustScore: trust(96),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'nonprofit-exec-director',
    displayName: 'Nonprofit Executive Director',
    version: '1.0.0',
    description: '11-agent team for nonprofit/trade association automation: finances, membership, events, compliance, communications, sponsor relations, and workflow design.',
    type: 'agent_config',
    category: 'operations',
    difficulty: 'intermediate',
    status: 'published',
    author,
    tags: ['nonprofit', 'trade-association', 'automation', 'membership', 'finance', 'events'],
    capabilities: [
      { name: 'Financial Management', description: 'Budget tracking, grant reporting, forecasting', tools: ['Read', 'Write', 'Bash'] },
      { name: 'Membership Stewardship', description: 'Onboarding, engagement tracking, renewals', tools: ['Read', 'Write'] },
      { name: 'Event Orchestration', description: 'Planning, registration, sponsorship, post-event', tools: ['Write', 'Bash'] },
      { name: 'Compliance Monitoring', description: 'Regulatory tracking, audit prep, policy enforcement', tools: ['Read', 'Grep'] },
    ],
    dependencies: [
      { name: 'exec-automator', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'exec-automator',
      pluginVersion: '1.0.0',
      agents: ['admin-coordinator', 'finance-manager', 'membership-steward', 'event-orchestrator', 'compliance-monitor', 'communications-director', 'sponsor-relations', 'social-media-manager', 'meeting-facilitator', 'workflow-designer', 'org-analyzer'],
      skills: ['nonprofit-finance', 'association-management', 'membership-engagement', 'event-planning', 'meeting-facilitation', 'process-automation', 'langgraph-orchestration', 'langchain-integrations'],
      commands: ['analyze', 'dashboard', 'report', 'orchestrate', 'generate', 'integrate', 'template'],
    }],
    estimatedDuration: '20 min',
    maxParallelAgents: 6,
    installCount: 134,
    activeUsers: 41,
    averageRating: 4.5,
    ratingCount: 23,
    completionRate: 0.89,
    avgSessionMinutes: 18,
    trustScore: trust(89),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'design-system-architect',
    displayName: 'Design System Architect',
    version: '1.0.0',
    description: 'AI-powered design system creation with 263+ curated styles, Keycloak multi-tenant theming, component generation, accessibility auditing, and token management.',
    type: 'agent_config',
    category: 'design',
    difficulty: 'intermediate',
    status: 'published',
    author,
    tags: ['design-system', 'theming', 'keycloak', 'accessibility', 'tailwind', 'multi-tenant'],
    capabilities: [
      { name: 'Style Generation', description: '263+ styles with CSS/Tailwind output', tools: ['Write'] },
      { name: 'Theme Engineering', description: 'Keycloak multi-tenant themes with token system', tools: ['Write', 'Read'] },
      { name: 'Accessibility Audit', description: 'WCAG compliance, contrast ratios, screen reader testing', tools: ['Bash', 'Read'] },
      { name: 'Component Design', description: 'React/Vue component scaffolding with variants', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'frontend-design-system', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'frontend-design-system',
      pluginVersion: '1.0.0',
      agents: ['design-architect', 'theme-engineer', 'component-designer', 'accessibility-auditor', 'responsive-specialist', 'style-implementer'],
      skills: ['design-styles', 'keycloak-theming', 'component-patterns', 'css-generation'],
      commands: ['style', 'theme', 'component', 'palette', 'tokens', 'audit', 'keycloak', 'convert'],
    }],
    estimatedDuration: '20 min',
    maxParallelAgents: 4,
    installCount: 189,
    activeUsers: 67,
    averageRating: 4.7,
    ratingCount: 41,
    completionRate: 0.92,
    avgSessionMinutes: 17,
    trustScore: trust(93),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// SKILL PACKS  (bundled skill sets)
// ---------------------------------------------------------------------------

const skillPacks: CoworkItem[] = [
  {
    id: id(),
    name: 'devops-essentials',
    displayName: 'DevOps Essentials Pack',
    version: '1.0.0',
    description: 'Complete DevOps skill bundle: Docker builds, Helm chart management, Kubernetes operations, Terraform IaC, Ansible provisioning, CI/CD with Harness, and deployment monitoring.',
    type: 'skill_pack',
    category: 'devops',
    difficulty: 'advanced',
    status: 'featured',
    author,
    tags: ['docker', 'kubernetes', 'helm', 'terraform', 'ansible', 'harness', 'ci-cd'],
    capabilities: [
      { name: 'Container Operations', description: 'Docker build, push, multi-stage, layer caching', tools: ['Bash'] },
      { name: 'Orchestration', description: 'Helm charts, K8s manifests, rollback strategies', tools: ['Write', 'Bash'] },
      { name: 'Infrastructure', description: 'Terraform modules, Ansible playbooks, state management', tools: ['Write', 'Bash'] },
      { name: 'CI/CD Pipelines', description: 'Harness pipeline design, approval gates, rollback', tools: ['Write', 'Bash'] },
    ],
    dependencies: [
      { name: 'aws-eks-helm-keycloak', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'fullstack-iac', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'deployment-pipeline', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'team-accelerator', version: '>=1.0.0', type: 'plugin', optional: true },
    ],
    pluginBindings: [
      {
        pluginName: 'aws-eks-helm-keycloak',
        pluginVersion: '1.0.0',
        agents: ['deployment-strategist', 'pipeline-architect'],
        skills: ['harness-eks-deployments', 'helm-development', 'harness-keycloak-auth'],
        commands: ['setup', 'ship', 'pipeline-scaffold'],
      },
      {
        pluginName: 'fullstack-iac',
        pluginVersion: '1.0.0',
        agents: [],
        skills: [],
        commands: ['docker', 'k8s', 'ansible', 'infra'],
      },
      {
        pluginName: 'deployment-pipeline',
        pluginVersion: '1.0.0',
        agents: ['orchestrator', 'validator', 'rollback'],
        skills: [],
        commands: ['start', 'status', 'approve', 'rollback'],
      },
      {
        pluginName: 'team-accelerator',
        pluginVersion: '1.0.0',
        agents: ['devops-engineer'],
        skills: ['devops-practices'],
        commands: ['deploy', 'status'],
      },
    ],
    estimatedDuration: '30 min',
    maxParallelAgents: 4,
    installCount: 312,
    activeUsers: 98,
    averageRating: 4.7,
    ratingCount: 67,
    completionRate: 0.87,
    avgSessionMinutes: 25,
    trustScore: trust(93),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'react-animation-toolkit',
    displayName: 'React Animation Toolkit',
    version: '1.1.0',
    description: 'Complete animation skills: Framer Motion, GSAP, CSS animations, scroll effects, text effects, 3D transforms, spring physics, micro-interactions, and page transitions.',
    type: 'skill_pack',
    category: 'design',
    difficulty: 'intermediate',
    status: 'published',
    author,
    tags: ['react', 'animation', 'framer-motion', 'gsap', 'css', 'micro-interactions'],
    capabilities: [
      { name: 'Motion Design', description: 'Framer Motion variants, gestures, layout animations', tools: ['Write'] },
      { name: 'Scroll Effects', description: 'Parallax, reveal, progress-driven animations', tools: ['Write'] },
      { name: 'Text Effects', description: 'Typewriter, morphing, gradient, kinetic typography', tools: ['Write'] },
      { name: '3D Transforms', description: 'CSS 3D, perspective, card flips, depth effects', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'react-animation-studio', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'react-animation-studio',
      pluginVersion: '1.1.0',
      agents: ['animation-architect', 'motion-designer', 'creative-effects-artist', 'interaction-specialist', 'transition-engineer', 'performance-optimizer'],
      skills: ['framer-motion', 'gsap', 'css-animations', 'scroll-animations', 'text-animations', '3d-animations', 'spring-physics', 'creative-effects', 'svg-animations', 'accent-animations', 'background-animations'],
      commands: ['animate', 'animate-component', 'animate-scroll', 'animate-text', 'animate-3d', 'animate-sequence', 'animate-transition', 'animate-effects', 'animate-preset', 'animate-background', 'animate-audit', 'animate-export'],
    }],
    estimatedDuration: '15 min',
    maxParallelAgents: 3,
    installCount: 267,
    activeUsers: 94,
    averageRating: 4.8,
    ratingCount: 59,
    completionRate: 0.95,
    avgSessionMinutes: 13,
    trustScore: trust(94),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'marketplace-intelligence',
    displayName: 'Marketplace Intelligence Pack',
    version: '1.0.0',
    description: 'Plugin marketplace intelligence: project fingerprinting, gap detection, intent-based composition, trust scoring, federated registry management, and policy enforcement.',
    type: 'skill_pack',
    category: 'engineering',
    difficulty: 'advanced',
    status: 'published',
    author,
    tags: ['marketplace', 'composition', 'trust', 'federation', 'intelligence', 'security'],
    capabilities: [
      { name: 'Intent Composition', description: 'Natural language to plugin DAG resolution', tools: ['Read', 'Bash'] },
      { name: 'Project Fingerprinting', description: 'Analyze codebase and recommend plugins', tools: ['Read', 'Grep', 'Glob'] },
      { name: 'Trust Scoring', description: 'Composite trust analysis with A-F grading', tools: ['Read', 'Bash'] },
      { name: 'Registry Federation', description: 'Multi-registry sync, priority resolution, lockfile', tools: ['Read', 'Write'] },
    ],
    dependencies: [
      { name: 'marketplace-pro', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'marketplace-pro',
      pluginVersion: '1.0.0',
      agents: ['marketplace-advisor'],
      skills: ['composition', 'intelligence', 'security', 'federation', 'devstudio'],
      commands: ['compose', 'recommend', 'trust', 'verify', 'registry', 'policy', 'lock', 'dev', 'quick', 'status'],
    }],
    estimatedDuration: '10 min',
    maxParallelAgents: 2,
    installCount: 178,
    activeUsers: 56,
    averageRating: 4.5,
    ratingCount: 31,
    completionRate: 0.91,
    avgSessionMinutes: 8,
    trustScore: trust(92),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// SESSION BLUEPRINTS  (complete session configurations)
// ---------------------------------------------------------------------------

const blueprints: CoworkItem[] = [
  {
    id: id(),
    name: 'enterprise-release',
    displayName: 'Enterprise Release Coordinator',
    version: '1.0.0',
    description: 'Full release workflow: freeze branch, run quality gates, security audit, generate changelog, deploy to staging, smoke test, production rollout with rollback plan, Jira release notes, and Confluence documentation.',
    type: 'session_blueprint',
    category: 'devops',
    difficulty: 'expert',
    status: 'featured',
    author,
    tags: ['release', 'deployment', 'quality-gates', 'changelog', 'jira', 'confluence'],
    capabilities: [
      { name: 'Quality Gate', description: 'TypeScript check, ESLint, security scan, test suite', tools: ['Bash'] },
      { name: 'Release Management', description: 'Changelog generation, version bumping, tagging', tools: ['Bash', 'Write'] },
      { name: 'Deployment', description: 'Staging deploy, smoke test, production rollout', tools: ['Bash'] },
      { name: 'Documentation', description: 'Jira release notes, Confluence publish', tools: ['Bash', 'Write'] },
    ],
    dependencies: [
      { name: 'jira-orchestrator', version: '>=7.0.0', type: 'plugin', optional: false },
      { name: 'deployment-pipeline', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'team-accelerator', version: '>=1.0.0', type: 'plugin', optional: true },
    ],
    pluginBindings: [
      {
        pluginName: 'jira-orchestrator',
        pluginVersion: '7.5.0',
        agents: ['completion-flow-orchestrator', 'confluence-documentation-creator', 'compliance-reporter'],
        skills: ['jira-orchestration', 'confluence', 'pr-workflow'],
        commands: ['release', 'deploy', 'docs', 'compliance', 'confluence', 'ship'],
        mcpServers: ['deploy-intelligence', 'workflow-bridge', 'code-quality-gate'],
      },
      {
        pluginName: 'deployment-pipeline',
        pluginVersion: '1.0.0',
        agents: ['orchestrator', 'validator', 'rollback'],
        skills: [],
        commands: ['start', 'approve', 'status', 'rollback'],
      },
    ],
    estimatedDuration: '40 min',
    maxParallelAgents: 6,
    installCount: 145,
    activeUsers: 38,
    averageRating: 4.7,
    ratingCount: 24,
    completionRate: 0.88,
    avgSessionMinutes: 35,
    trustScore: trust(95),
    isOfficial: true,
    isVerified: true,
    isFeatured: true,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'keycloak-multi-tenant',
    displayName: 'Keycloak Multi-Tenant Platform',
    version: '1.0.0',
    description: 'Complete multi-tenant setup: Keycloak realm configuration, client registrations, RBAC policies, theme customization, FastAPI/MERN integration, and Docker deployment.',
    type: 'session_blueprint',
    category: 'security',
    difficulty: 'advanced',
    status: 'published',
    author,
    tags: ['keycloak', 'multi-tenant', 'auth', 'rbac', 'oidc', 'docker'],
    capabilities: [
      { name: 'Realm Setup', description: 'Create realms, clients, roles, identity providers', tools: ['Bash', 'Write'] },
      { name: 'Auth Integration', description: 'FastAPI/MERN OIDC middleware, token validation', tools: ['Write'] },
      { name: 'Theme Customization', description: 'Custom login/account themes per tenant', tools: ['Write'] },
      { name: 'Docker Deploy', description: 'Keycloak HA deployment with PostgreSQL', tools: ['Write', 'Bash'] },
    ],
    dependencies: [
      { name: 'lobbi-platform-manager', version: '>=1.0.0', type: 'plugin', optional: false },
      { name: 'frontend-design-system', version: '>=1.0.0', type: 'plugin', optional: true },
    ],
    pluginBindings: [
      {
        pluginName: 'lobbi-platform-manager',
        pluginVersion: '1.0.0',
        agents: ['keycloak-admin', 'service-orchestrator', 'env-manager', 'test-generator'],
        skills: ['keycloak-admin', 'multi-tenant', 'mern-patterns'],
        commands: ['keycloak-setup', 'keycloak-user', 'keycloak-theme', 'env-generate', 'env-validate', 'service', 'health'],
      },
      {
        pluginName: 'frontend-design-system',
        pluginVersion: '1.0.0',
        agents: ['theme-engineer'],
        skills: ['keycloak-theming'],
        commands: ['keycloak'],
      },
    ],
    estimatedDuration: '30 min',
    maxParallelAgents: 4,
    installCount: 112,
    activeUsers: 34,
    averageRating: 4.6,
    ratingCount: 19,
    completionRate: 0.86,
    avgSessionMinutes: 27,
    trustScore: trust(91),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: id(),
    name: 'project-scaffolder',
    displayName: 'Universal Project Scaffolder',
    version: '1.0.0',
    description: 'Generate any project type from archetypes: FastAPI, React, monorepo, microservice, CLI tool, or library — with Harness CI/CD pipelines, Docker, testing, and documentation.',
    type: 'session_blueprint',
    category: 'engineering',
    difficulty: 'beginner',
    status: 'published',
    author,
    tags: ['scaffolding', 'templates', 'harness', 'code-generation', 'archetype'],
    capabilities: [
      { name: 'Archetype Selection', description: 'Choose from 10+ project templates', tools: ['Read'] },
      { name: 'Code Generation', description: 'Full project skeleton with best practices', tools: ['Write', 'Bash'] },
      { name: 'Pipeline Setup', description: 'Harness CI/CD pipeline scaffolding', tools: ['Write'] },
      { name: 'Documentation', description: 'README, API docs, architecture decision records', tools: ['Write'] },
    ],
    dependencies: [
      { name: 'claude-code-templating-plugin', version: '>=1.0.0', type: 'plugin', optional: false },
    ],
    pluginBindings: [{
      pluginName: 'claude-code-templating-plugin',
      pluginVersion: '1.0.0',
      agents: ['scaffold-agent', 'codegen-agent', 'harness-expert', 'testing-agent', 'database-agent', 'archetype-creator'],
      skills: ['universal-templating', 'project-scaffolding', 'harness-expert'],
      commands: ['scaffold', 'generate', 'template', 'archetype', 'harness'],
    }],
    estimatedDuration: '10 min',
    maxParallelAgents: 3,
    installCount: 356,
    activeUsers: 123,
    averageRating: 4.6,
    ratingCount: 72,
    completionRate: 0.95,
    avgSessionMinutes: 8,
    trustScore: trust(93),
    isOfficial: true,
    isVerified: true,
    isFeatured: false,
    isCurated: true,
    createdAt: now,
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// EXPORT: Complete Catalog
// ---------------------------------------------------------------------------

export const COWORK_CATALOG: CoworkItem[] = [
  ...templates,
  ...workflows,
  ...agentConfigs,
  ...skillPacks,
  ...blueprints,
];

// Patch author item count
author.itemCount = COWORK_CATALOG.length;

export const COWORK_CATALOG_BY_TYPE = {
  template: templates,
  workflow: workflows,
  agent_config: agentConfigs,
  skill_pack: skillPacks,
  session_blueprint: blueprints,
};
